[package]
name = "rgpt-state"
version = "0.1.0"
edition = "2021"

[dependencies]

rgpt-types = { workspace = true }

tokio = { workspace = true, features = ["full"] }

tracing = { workspace = true}

crossterm = { workspace = true}
